### ISSUE TITLE
Malformed descriptor

### ISSUE THREAD

**Issue by guhaizhous** [chrisdew/protobuf#51]
var schema = new Schema(fs.readFileSync('./buftest.proto'));
Error: Malformed descriptor
    at Error (native)
    at Object.<anonymous> (D:\mytest\game\test.js:76:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

buftest.proto

package com.game.buftest;

message BufTest{
	optional float num =1;
	optional bytes payload =2;
}

I don't know where it was,

**Comment by goudan0096** [comment]
I have the same issue,Is there anyone who knows the reason?
